// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8tzyIDpy1dArSzcr9q-W2u9zQ8gxD390',
    appId: '1:870333530551:web:a74d6e98efa6dd9a232832',
    messagingSenderId: '870333530551',
    projectId: 'sign-up-93719',
    authDomain: 'sign-up-93719.firebaseapp.com',
    storageBucket: 'sign-up-93719.firebasestorage.app',
    measurementId: 'G-B414VL13WW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOdsLLbyRv10d7zN2Omq6YyHXShKNCVy4',
    appId: '1:870333530551:android:591c8de143c8bdcd232832',
    messagingSenderId: '870333530551',
    projectId: 'sign-up-93719',
    storageBucket: 'sign-up-93719.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzbRBzE1HiTPnvGfErQGoAzV2OCG_QBPU',
    appId: '1:870333530551:ios:995d50a7c2cf6177232832',
    messagingSenderId: '870333530551',
    projectId: 'sign-up-93719',
    storageBucket: 'sign-up-93719.firebasestorage.app',
    iosBundleId: 'com.example.googleSignUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzbRBzE1HiTPnvGfErQGoAzV2OCG_QBPU',
    appId: '1:870333530551:ios:995d50a7c2cf6177232832',
    messagingSenderId: '870333530551',
    projectId: 'sign-up-93719',
    storageBucket: 'sign-up-93719.firebasestorage.app',
    iosBundleId: 'com.example.googleSignUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8tzyIDpy1dArSzcr9q-W2u9zQ8gxD390',
    appId: '1:870333530551:web:0af040a463b062c6232832',
    messagingSenderId: '870333530551',
    projectId: 'sign-up-93719',
    authDomain: 'sign-up-93719.firebaseapp.com',
    storageBucket: 'sign-up-93719.firebasestorage.app',
    measurementId: 'G-TKJ7V5VM2N',
  );
}
